import Sidebar from "@/components/Sidebar";
import "./globals.css";
import { Inter } from "next/font/google";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={`bg-white `}>
				<div className="flex bg-[#eaeaea] h-screen max-w-[1500px] mx-auto " >
					<div className="w-[250px]  ">
                    <Sidebar />
                    </div>
					<div className="w-full px-[12px] flex flex-col gap-y-[24px] overflow-hidden" >
						<Header />  						
                        <div className="h-[90vh]  overflow-scroll scroll-hidden" >
                        {children}
                        </div>
					</div>
				</div>
			</body>
		</html>
	);
}
